version: '2.3'

services:
  db:
    image: postgres:10
    env_file:
      - db.env
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/postgresql/data

  web:
    build: .
    runtime: nvidia
    volumes:
      - static_volume:/comixify/static
      - media_volume:/comixify/media
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db
    environment:
      - DEBUG=true
      - PYTHONUNBUFFERED=1
    tty: true

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/comixify/static
      - media_volume:/comixify/media
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  db_volume:
  static_volume:
  media_volume: