# Generated by Django 2.0.7 on 2018-11-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='frames_mode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='image_assessment_mode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='rl_mode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='style_transfer_mode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='yt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
