# Generated by Django 2.0.7 on 2018-11-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_additional_info_to_Comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
